### ISSUE TITLE
Usage on Linux

### ISSUE THREAD

**Issue by TomFoerster** [ckuhlmann/lt2circuitikz#3] opened 2020-02-03 14:42 UTC
Unfortunately your tool doesnt work on a Linux machine (I use LTSpice via wine) . I tried to convert the script to Linux but I didnt get it to work. I only replaced some backslashes with normal ones. Would it be possible for you to make it OS independent?
Attached is the crash traceback.
Thank you!!
[output.txt](https://github.com/ckuhlmann/lt2circuitikz/files/4148425/output.txt)

**Comment by ckuhlmann** [comment] 2020-03-05 16:03
Hi,
fixed in c2960474a5987b44a86658ff53c33d793cf240b5 and tested with Python 3.7 on Lubuntu 19.10 / compiled with Texlive

If you have any further issues, please attach a **full** output log, since errors may have their root cause in early stages.
I might not have time to address issues in a timely manner, so if you make any improvements yourself, feel free to create a pull-request so others benefit as well. Thanks.

**Closed as completed by ckuhlmann** 2020-03-05 16:03 UTC
